name: CI/CD Pipeline

on:
  push:
    branches: 
      - main  # Deploy to production
      - dev   # Deploy to development

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
          architecture: x64

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      - name: Setup Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate and Install Dependencies into Virtual env
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

  continuous-deployment-prod:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to production via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "app/, requirements.txt, .env, adaletgpt_backend.service"
          target: ./AdaletGPT_Backend/

      - name: Install dependencies and restart production service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/AdaletGPT_Backend/
            sudo rm -rf venv
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo cp /home/ubuntu/AdaletGPT_Backend/adaletgpt_backend.service /etc/systemd/system/adaletgpt_backend.service
            sudo systemctl daemon-reload
            sudo systemctl stop adaletgpt_backend
            sudo systemctl start adaletgpt_backend
            sudo systemctl enable adaletgpt_backend

  continuous-deployment-dev:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to development via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          source: "app/, requirements.txt, .env, adaletgpt_backend.service"
          target: ./AdaletGPT_Backend/

      - name: Install dependencies and restart development service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          script: |
            cd /home/ubuntu/AdaletGPT_Backend/
            sudo rm -rf venv
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo cp /home/ubuntu/AdaletGPT_Backend/adaletgpt_backend.service /etc/systemd/system/adaletgpt_backend.service
            sudo systemctl daemon-reload
            sudo systemctl stop adaletgpt_backend
            sudo systemctl start adaletgpt_backend
            sudo systemctl enable adaletgpt_backend