name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "app/ requirements.txt .env adaletgpt_backend.service"
          target: ./AdaletGPT_Backend/

      - name: Install dependencies and restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/AdaletGPT_Backend/
            python3 -m venv venv
            source venv/bin/activate
            pip install -r ../requirements.txt
            deactivate
            sudo cp /home/ubuntu/AdaletGPT_Backend/adaletgpt_backend.service /etc/systemd/system/adaletgpt_backend.service
            sudo systemctl daemon-reload
            sudo systemctl stop app
            sudo systemctl start app
            sudo systemctl enable app
